name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'mathcomp/mathcomp-dev:coq-dev'
          - 'mathcomp/mathcomp-dev:coq-8.15'
          - 'mathcomp/mathcomp-dev:coq-8.14'
          - 'mathcomp/mathcomp-dev:coq-8.13'
          - 'mathcomp/mathcomp-dev:coq-8.12'
          - 'mathcomp/mathcomp-dev:coq-8.11'
          - 'mathcomp/mathcomp:1.13.0-coq-8.14'
          - 'mathcomp/mathcomp:1.13.0-coq-8.13'
          - 'mathcomp/mathcomp:1.13.0-coq-8.12'
          - 'mathcomp/mathcomp:1.13.0-coq-8.11'
          - 'mathcomp/mathcomp:1.12.0-coq-8.14'
          - 'mathcomp/mathcomp:1.12.0-coq-8.13'
          - 'mathcomp/mathcomp:1.12.0-coq-8.12'
          - 'mathcomp/mathcomp:1.12.0-coq-8.11'
          - 'mathcomp/mathcomp:1.12.0-coq-8.10'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          custom_script: |
            {{before_install}}
            startGroup "Build gaia-sets dependencies"
              opam pin add -n -y -k path coq-gaia-sets .
              opam update -y
              opam install -y -j 2 coq-gaia-sets --deps-only
            endGroup
            startGroup "Build gaia-sets"
              opam install -y -v -j 2 coq-gaia-sets
              opam list
            endGroup
            startGroup "Build gaia-ordinal-types dependencies"
              opam pin add -n -y -k path coq-gaia-ordinal-types .
              opam update -y
              opam install -y -j 2 coq-gaia-ordinal-types --deps-only
            endGroup
            startGroup "Build gaia-ordinal-types"
              opam install -y -v -j 2 coq-gaia-ordinal-types
              opam list
            endGroup
            startGroup "Build gaia-ordinals dependencies"
              opam pin add -n -y -k path coq-gaia-ordinals .
              opam update -y
              opam install -y -j 2 coq-gaia-ordinals --deps-only
            endGroup
            startGroup "Build gaia-ordinals"
              opam install -y -v -j 2 coq-gaia-ordinals
              opam list
            endGroup
            startGroup "Build gaia-numbers dependencies"
              opam pin add -n -y -k path coq-gaia-numbers .
              opam update -y
              opam install -y -j 2 coq-gaia-numbers --deps-only
            endGroup
            startGroup "Build gaia-numbers"
              opam install -y -v -j 2 coq-gaia-numbers
              opam list
            endGroup
            startGroup "Build gaia-stern dependencies"
              opam pin add -n -y -k path coq-gaia-stern .
              opam update -y
              opam install -y -j 2 coq-gaia-stern --deps-only
            endGroup
            startGroup "Build gaia-stern"
              opam install -y -v -j 2 coq-gaia-stern
              opam list
            endGroup
            startGroup "Uninstallation test"
              opam remove -y coq-gaia-stern
              opam remove -y coq-gaia-numbers
              opam remove -y coq-gaia-ordinals
              opam remove -y coq-gaia-ordinal-types
              opam remove -y coq-gaia-sets
            endGroup

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
